title: Renee Crispo
logo: /assets/img/profilePic.png
description: PhD Student at INRIA, Paris. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme